spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
---
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/social_network?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Samara
    username: spring
    password: 123
---
spring:
  freemarker:
    expose-request-attributes: true
---
spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

user:
  upload:
    path: /D:/Program Files/Social_network/userImages

server:
  error:
    whitelabel:
      enabled: false