server:
  port: 8079
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authorization
          uri: http://localhost:8083/
          predicates:
            - Path=/authorization/**
        - id: notification
          uri: http://localhost:8085/
          predicates:
            - Path=/notification/**
        - id: userPage
          uri: http://localhost:8082/
          predicates:
            - Path=/user/**
        - id: friendList
          uri: http://localhost:8084/
          predicates:
            - Path=/friend/**
        - id: posts
          uri: http://localhost:8086/
          predicates:
            - Path=/posts/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: true