server:
  port: 8079
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authorization
          uri: lb://AUTHORIZATION/
          predicates:
            - Path=/authorization/**
        - id: notification
          uri: lb://NOTIFICATION/
          predicates:
            - Path=/notification/**
        - id: userPage
          uri: lb://USER-PAGE/
          predicates:
            - Path=/userPage/**
        - id: friendList
          uri: lb://FRIEND-LIST/
          predicates:
            - Path=/friendList/**
        - id: posts
          uri: lb://POSTS/
          predicates:
            - Path=/posts/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: true